language: php

php:
  - 7.1
  - 7.2

before_script:
  - composer install

notifications:
  email:
    recipients:
    - 352635484@qq.com
    on_success: always
    on_failure: always
script: ./vendor/bin/phpunit -c phpunit.xml --coverage-text
